// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCagBr4-6q_-p-WSpfhB8INHtpfCZdqN5c',
    appId: '1:326320642247:web:4443071e3bce8e94ab06e2',
    messagingSenderId: '326320642247',
    projectId: 'ecommerceflutter-68c37',
    authDomain: 'ecommerceflutter-68c37.firebaseapp.com',
    storageBucket: 'ecommerceflutter-68c37.appspot.com',
    measurementId: 'G-BZWDMEVJH8',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC7kidwAcHlQPs2OXFYBF3OJ9lZcMCwE7U',
    appId: '1:326320642247:android:636f8cbd91a30612ab06e2',
    messagingSenderId: '326320642247',
    projectId: 'ecommerceflutter-68c37',
    storageBucket: 'ecommerceflutter-68c37.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAtoVY0OV07Icn31vKqxwDscwHsbOO-mBM',
    appId: '1:326320642247:ios:d7cac9f5c547ca28ab06e2',
    messagingSenderId: '326320642247',
    projectId: 'ecommerceflutter-68c37',
    storageBucket: 'ecommerceflutter-68c37.appspot.com',
    androidClientId: '326320642247-qbdncbi0kml7j25tsekr1ffa3oebv9tn.apps.googleusercontent.com',
    iosClientId: '326320642247-6c2gd0d2mm0jt1u8h8btjj8kab3u1sqm.apps.googleusercontent.com',
    iosBundleId: 'com.example.tStore',
  );

}